# Zero-dimensional Arrays

In [20]:
import numpy as np
x = np.array(42)
print("x: ", x)
print("The type of x: ", type(x))
print("The dimension of x:", np.ndim(x))
x.dtype

('x: ', array(42))
('The type of x: ', <type 'numpy.ndarray'>)
('The dimension of x:', 0)


dtype('int32')

# One-dimensional Arrays

In [2]:
F = np.array([1, 1, 2, 3, 5, 8, 13, 21])
V = np.array([3.4, 6.9, 99.8, 12.8])
print("F: ", F)
print("V: ", V)
print("Type of F: ", F.dtype)
print("Type of V: ", V.dtype)
print("Dimension of F: ", np.ndim(F))
print("Dimension of V: ", np.ndim(V))

('F: ', array([ 1,  1,  2,  3,  5,  8, 13, 21]))
('V: ', array([ 3.4,  6.9, 99.8, 12.8]))
('Type of F: ', dtype('int32'))
('Type of V: ', dtype('float64'))
('Dimension of F: ', 1)
('Dimension of V: ', 1)


# Two- and Multidimensional Arrays

In [7]:
A = np.array([ [3.4, 8.7, 9.9], 
               [1.1, -7.8, -0.7],
               [4.1, 12.3, 4.8]])
print(A)
print(A.ndim)
print(np.ndim(A))

[[ 3.4  8.7  9.9]
 [ 1.1 -7.8 -0.7]
 [ 4.1 12.3  4.8]]
2
2


In [10]:
B = np.array([ [[111, 112], [121, 122]],
               [[211, 212], [221, 222]],
               [[311, 312], [321, 322]] ])
print(B)
print(B.ndim)
print(np.ndim(B))
print(np.shape(B))

[[[111 112]
  [121 122]]

 [[211 212]
  [221 222]]

 [[311 312]
  [321 322]]]
3
3
(3, 2, 2)


# Shape of an Array

The function "shape" returns the shape of an array. The shape is a tuple of integers.

In [8]:
x = np.array([ [67, 63, 87],
               [77, 69, 59],
               [85, 87, 99],
               [79, 72, 71],
               [63, 89, 93],
               [68, 92, 78]])
print(np.shape(x))

(6, 3)


"shape" can also be used to change the shape of an array.

In [11]:
x.shape = (3, 6)
print(x)

[[67 63 87 77 69 59]
 [85 87 99 79 72 71]
 [63 89 93 68 92 78]]


In [11]:
x.shape = (2, 9)
print(x)

[[67 63 87 77 69 59 85 87 99]
 [79 72 71 63 89 93 68 92 78]]


# Indexing and Slicing

In [13]:
F = np.array([1, 1, 2, 3, 5, 8, 13, 21])
# print the first element of F
print(F[0])
# print the last element of F
print(F[-1])

1
21


In [13]:
A = np.array([ [3.4, 8.7, 9.9], 
               [1.1, -7.8, -0.7],
               [4.1, 12.3, 4.8]])
print(A[1][0])

1.1


Array_Name [start:stop:step]

In [24]:
S = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(S[2:5])
print(S[:4])
print(S[6:])
print(S[:])

[2 3 4]
[0 1 2 3]
[6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


# multidimensional slicing

In [25]:
A = np.array([
[11, 12, 13, 14, 15],
[21, 22, 23, 24, 25],
[31, 32, 33, 34, 35],
[41, 42, 43, 44, 45],
[51, 52, 53, 54, 55]])
print(A[:3, 2:])

[[13 14 15]
 [23 24 25]
 [33 34 35]]


In [17]:
print(A[3:, :])

[[41 42 43 44 45]
 [51 52 53 54 55]]


In [20]:
print(A[:, 4:])

[[15]
 [25]
 [35]
 [45]
 [55]]


In [26]:
A = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
S = A[2:6]
print(S)
S[0] = 22
S[1] = 23
print(S)
print(A)

[2 3 4 5]
[22 23  4  5]
[ 0  1 22 23  4  5  6  7  8  9]


Note : Whereas slicings on lists and tuples create new objects, a slicing operation on an array creates a view on the original array. So we get an another possibility to access the array, or better a part of the array. From this follows that if we modify a view, the original array will be modified as well.

In [28]:
lst = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
lst2 = lst[2:6]
print(lst2)
lst2[0] = 22
lst2[1] = 23
print(lst)
print(lst2)

[2, 3, 4, 5]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[22, 23, 4, 5]


### If you want to check, if two array names share the same memory block, you can use the function np.may_share_memory.

In [32]:
print(np.may_share_memory(A, S))

True


In [36]:
A = np.arange(12)
B = A.reshape(3, 4)
print(B)
A[0] = 42
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[42  1  2  3  4  5  6  7  8  9 10 11]


In [37]:
np.may_share_memory(A, B)

True

## Creating Arrays with Ones, Zeros and Empty

In [47]:
import numpy as np
E = np.ones((2,3))
print(E)
print(E.dtype)
F = np.ones((3,4),dtype=int)
print(F)
print(F.dtype)

[[1. 1. 1.]
 [1. 1. 1.]]
float64
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
int32


In [42]:
Z = np.zeros((2,4))
print(Z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


x = np.array([2,5,18,14,4])
E = np.ones_like(x)
print(E)
Z = np.zeros_like(x)
print(Z)

There is another interesting way to create an array with Ones or with Zeros, if it has to have the same shape as another existing array 'a'. Numpy supplies for this purpose the methods ones_like(a) and zeros_like(a).

In [76]:
x = np.array([2,5,18,14,4]) 
E = np.ones_like(x)
print(E)
Z = np.zeros_like(x)
print(Z)

[1 1 1 1 1]
[0 0 0 0 0]


# Copying Arrays

# numpy.copy()

In [115]:
import numpy as np
x = np.array([[42,22,12],[44,53,66]], order='A')
y = x.copy()
x[0,0] = 1001
print(x)
print(y)

[[1001   22   12]
 [  44   53   66]]
[[42 22 12]
 [44 53 66]]



Parameter	Meaning
obj	array_like input data.
order	The possible values are {'C', 'F', 'A', 'K'}. This parameter controls the memory layout of the copy. 'C' means C-order, 'F' means Fortran-order, 'A' means 'F' if the object 'obj' is Fortran contiguous, 'C' otherwise. 'K' means match the layout of 'obj' as closely as possible.

In [116]:
print(x.flags['C_CONTIGUOUS'])
print(y.flags['C_CONTIGUOUS'])

True
True


# Identity Array

In linear algebra, the identity matrix, or unit matrix, of size n is the n × n square matrix with ones on the main diagonal and zeros elsewhere.

There are two ways in Numpy to create identity arrays:

1) identy
2)  eye

# The identity Function

In [117]:
import numpy as np
np.identity(4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

# The eye Function

Another way to create identity arrays provides the function eye. This function creates also diagonal arrays consisting solely of ones.

It returns a 2-D array with ones on the diagonal and zeros elsewhere.

eye(N, M=None, k=0, dtype=float)

In [31]:
import numpy as np
np.eye(5, 8, k=1, dtype=int)

array([[0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0]])

# Assignment

1) Create an arbitrary one dimensional array called "v".

2) Create a new array which consists of the odd indices of previously created array "v".

3) Create a new array in backwards ordering from v.

4) What will be the output of the following code:

   a = np.array([1, 2, 3, 4, 5])
   b = a[1:4]
   b[0] = 200
   print(a[1])
   
5) Create a two dimensional array called "m".

6) Create a new array from m, in which the elements of each row are in reverse order.

7) Another one, where the rows are in reverse order.

8) Create an array from m, where columns and rows are in reverse order.

9) Cut of the first and last row and the first and last column.

In [33]:
v=([2,3,4,5,56,7])
print("Type of V: ", V.dtype)
print("Dimension of V: ", np.ndim(V))

('Type of V: ', dtype('float64'))
('Dimension of V: ', 1)


In [36]:
B = v[1::2]
B


[7, 56, 5, 4, 3, 2]

In [37]:
c = v[::-1]
c

[7, 56, 5, 4, 3, 2]

In [43]:
a = np.array([1, 2, 3, 4, 5])
b = a[1:4]
b[0] = 200 
print(a[1])


200


In [46]:
m = np.array([ [3.4, 8.7, 9.9], 
               [1.1, -7.8, -0.7],
               [4.1, 12.3, 4.8]])
print(m.ndim)

2


In [53]:
print(m[:,::-1])

[[ 9.9  8.7  3.4]
 [-0.7 -7.8  1.1]
 [ 4.8 12.3  4.1]]


In [50]:
import numpy as np;
np.flip(m, 0)

array([[ 4.1, 12.3,  4.8],
       [ 1.1, -7.8, -0.7],
       [ 3.4,  8.7,  9.9]])

In [60]:
m[::-1, ::-1]

array([[ 4.8, 12.3,  4.1],
       [-0.7, -7.8,  1.1],
       [ 9.9,  8.7,  3.4]])

In [69]:
print(m)
print(m[1:2,1:2])

[[ 3.4  8.7  9.9]
 [ 1.1 -7.8 -0.7]
 [ 4.1 12.3  4.8]]
[[-7.8]]


# dtype 

In [78]:
dt = np.dtype([('country', 'S20'), ('density', 'i4'), ('area', 'i4'), ('population', 'i4')])
population_table = np.array([
    ('Netherlands', 393, 41526, 16928800),
    ('Belgium', 337, 30510, 11007020),
    ('United Kingdom', 256, 243610, 62262000),
    ('Germany', 233, 357021, 81799600),
    ('Liechtenstein', 205, 160, 32842),
    ('Italy', 192, 301230, 59715625),
    ('Switzerland', 177, 41290, 7301994),
    ('Luxembourg', 173, 2586, 512000),
    ('France', 111, 547030, 63601002),
    ('Austria', 97, 83858, 8169929),
    ('Greece', 81, 131940, 11606813),
    ('Ireland', 65, 70280, 4581269),
    ('Sweden', 20, 449964, 9515744),
    ('Finland', 16, 338424, 5410233),
    ('Norway', 13, 385252, 5033675)],
    dtype=dt)
print(population_table[:4])

[('Netherlands', 393,  41526, 16928800) ('Belgium', 337,  30510, 11007020)
 ('United Kingdom', 256, 243610, 62262000)
 ('Germany', 233, 357021, 81799600)]


In [79]:
print(population_table['density'])
print(population_table['country'])
print(population_table['area'][2:5])

[393 337 256 233 205 192 177 173 111  97  81  65  20  16  13]
['Netherlands' 'Belgium' 'United Kingdom' 'Germany' 'Liechtenstein'
 'Italy' 'Switzerland' 'Luxembourg' 'France' 'Austria' 'Greece' 'Ireland'
 'Sweden' 'Finland' 'Norway']
[243610 357021    160]


# Writing data into file using NumPy

In [80]:
np.savetxt("population_table.csv",
           population_table,
           fmt="%s;%d;%d;%d",           
           delimiter=",")

In [81]:
ls

 Volume in drive C is OS
 Volume Serial Number is 9A08-030B

 Directory of C:\Users\admin\Desktop\numpy

22-11-2018  20:17    <DIR>          .
22-11-2018  20:17    <DIR>          ..
21-11-2018  14:24    <DIR>          .ipynb_checkpoints
21-11-2018  11:49            27,316 1. Introduction.ipynb
22-11-2018  20:16            25,133 2. Creating Array.ipynb
21-11-2018  11:43    <DIR>          pandas-visu
18-11-2018  18:14         1,082,729 pandas-visu.rar
22-11-2018  20:17               426 population_table.csv
               4 File(s)      1,135,604 bytes
               4 Dir(s)  566,513,315,840 bytes free


In [ ]:
cat population_table.csv

# Reading data from file using numpy

In [ ]:
dt = np.dtype([('country', np.unicode, 20), ('density', 'i4'), ('area', 'i4'), ('population', 'i4')])
x = np.genfromtxt("population_table.csv",
               dtype=dt,
               delimiter=";")
print(x)

In [ ]:
dt = np.dtype([('country', np.unicode, 20), ('density', 'i4'), ('area', 'i4'), ('population', 'i4')])
x = np.loadtxt("population_table.csv",
               dtype=dt,
               converters={0: lambda x: x.decode('utf-8')},
               delimiter=";")
print(x)

# Assignment